// @generated by `cargo xtask led-strip-generated` or `cargo check-all`. Do not edit by hand.
//! A concrete example of a struct type generated by the [`led_strip!`](crate::led_strip!) macro.
//!
//! This file is auto-generated by `cargo xtask led-strip-generated`.
//! See the [`led_strip`](mod@crate::led_strip) module docs for usage and examples.

#[cfg(all(not(doc), not(feature = "host")))]
use crate::led_strip;

#[cfg(all(not(doc), not(feature = "host")))]
led_strip! {
    LedStripGenerated {
        pin: PIN_3,
        len: 48,
    }
}

#[cfg(doc)]
/// Auto-generated example type for rustdoc.
///
/// See the [`led_strip`](mod@crate::led_strip) module docs for usage.
pub struct LedStripGenerated;

#[cfg(doc)]
use crate::led_strip::{Current, Frame1d, LedStripStatic};
#[cfg(doc)]
use crate::Result;

#[cfg(doc)]
/// Static resources for `LedStripGenerated`.
///
/// See the [`led_strip`](mod@crate::led_strip) module docs for usage.
pub struct LedStripGeneratedStatic {
    led_strip_static: LedStripStatic<48, 16>,
}

#[cfg(doc)]
impl LedStripGenerated {
    /// Number of LEDs in this strip.
    pub const LEN: usize = 48;
    /// Maximum animation frames allowed.
    pub const MAX_FRAMES: usize = 16;
    /// Maximum brightness level, automatically limited by the power budget specified in `max_current`.
    ///
    /// We assume each LED draws 60 mA at full brightness.
    pub const MAX_BRIGHTNESS: u8 =
        Current::Unlimited.max_brightness(Self::LEN as u32 * 60);

    /// Create static resources.
    ///
    /// See the [`led_strip`](mod@crate::led_strip) module docs for usage.
    #[must_use]
    #[doc(hidden)]
    pub const fn new_static() -> LedStripGeneratedStatic {
        LedStripGeneratedStatic {
            led_strip_static: LedStripStatic::new_static(),
        }
    }

    /// Create a new LED strip instance of the struct type defined by [`led_strip!`](crate::led_strip!).
    ///
    /// See the [`led_strip`](mod@crate::led_strip) module docs for usage.
    pub fn new(
        pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_3>,
        pio: embassy_rp::Peri<'static, embassy_rp::peripherals::PIO0>,
        dma: embassy_rp::Peri<'static, embassy_rp::peripherals::DMA_CH0>,
        spawner: embassy_executor::Spawner,
    ) -> Result<&'static Self> {
        static INSTANCE: LedStripGenerated = LedStripGenerated;
        let _ = (pin, pio, dma, spawner);
        Ok(&INSTANCE)
    }

    /// Write a frame to the LED strip.
    ///
    /// See the [`led_strip`](mod@crate::led_strip) module docs for usage.
    pub async fn write_frame(
        &self,
        frame: Frame1d<{ Self::LEN }>,
    ) -> Result<()> {
        let _ = frame;
        Ok(())
    }

    /// Animate frames on the LED strip.
    ///
    /// See the [`led_strip`](mod@crate::led_strip) module docs for usage.
    pub async fn animate<const N: usize>(
        &self,
        frames: [(Frame1d<{ Self::LEN }>, embassy_time::Duration); N],
    ) -> Result<()> {
        let _ = frames;
        Ok(())
    }
}
