//! This module provides the device abstraction for NeoPixel-style (WS2812) LED strips.
//! It supports setting individual LED colors and animating sequences of frames.
//! For 2D panels, it supports text, graphics, and animation.
//!
//! Up to four LED strips and panels can share a single [PIO](crate#glossary) resource.
//! This allows a total of 8 independent LED strips on the Pico 1 and 12 LED strips on the Pico 2.
//!
//! See [`led_strip!`] macro documentation for LED strip configuration.
//!
//!
//! Control individual LED colors with the `write_frame` method or animate a sequence
//! of frames with the `animate` method.
//!
//! ## Related
//!
//! - [`led_strip!`] — Macro to define a single LED strip device abstraction.
//! - [`led_strips!`](crate::led_strip::led_strips) — Define multiple LED strips that sharing one [PIO](crate#pio-programmable-io) resource.
//! - [`Led2d`](crate::led2d::Led2d) — A device abstraction for LED strips arranged as a panel. Supports text, graphics, and animation.
//! - [`crate::led_strip::led_strip_generated`] — Example showing the struct shape generated by [`led_strip!`].
//!
//! ## led_strip! Example 1
//!
//! Define a 48-LED strip and set every second LED to blue:
//!
//! ```rust,no_run
//! # #![no_std]
//! # #![no_main]
//! # use panic_probe as _;
//! # use core::convert::Infallible;
//! # use core::default::Default;
//! # use core::future;
//! # use core::result::Result::Ok;
//! # use embassy_executor::Spawner;
//! use device_kit::{Result, led_strip::{Frame, colors, led_strip}};
//!
//! led_strip! {
//!     LedStrip3 {
//!         pin: PIN_3,
//!         len: 48,
//!     }
//! }
//!
//! async fn example(spawner: Spawner) -> Result<Infallible> {
//!     let p = embassy_rp::init(Default::default());
//!
//!     let led_strip3 = LedStrip3::new(p.PIN_3, p.PIO0, p.DMA_CH0, spawner)?;
//!
//!     let mut frame = Frame::new();
//!     for pixel_index in (0..frame.len()).step_by(2) {
//!         frame[pixel_index] = colors::BLUE;
//!     }
//!     led_strip3.write_frame(frame).await?;
//!
//!     Ok(future::pending().await) // run forever
//! }
//! ```
//!
//! See the [`led_strip!`] macro documentation for all configuration options (PIO, DMA channel,
//! current limiting, gamma correction, frame animation size).
//!
//! ## led_strip! Example 2
//!
//! Use all optional fields of [`led_strip!`]. Animate a 96-LED strip through red, green, and blue.
//!
//! ```rust,no_run
//! # #![no_std]
//! # #![no_main]
//! # use panic_probe as _;
//! # use core::convert::Infallible;
//! # use core::default::Default;
//! # use core::future;
//! # use core::result::Result::Ok;
//! # use embassy_executor::Spawner;
//! use embassy_time::Duration;
//! use device_kit::{
//!     Result,
//!     led_strip::{Current, Frame, Gamma, colors, led_strip},
//! };
//!
//! led_strip! {
//!     LedStrip4 {
//!         pin: PIN_4,
//!         len: 96,
//!         pio: PIO1,
//!         dma: DMA_CH3,
//!         max_current: Current::Milliamps(1000),
//!         gamma: Gamma::Linear,
//!         max_frames: 3,
//!     }
//! }
//!
//! async fn animate_example(spawner: Spawner) -> Result<Infallible> {
//!     let p = embassy_rp::init(Default::default());
//!     let led_strip4 = LedStrip4::new(p.PIN_4, p.PIO1, p.DMA_CH3, spawner)?;
//!
//!     let frame_duration = Duration::from_millis(300);
//!
//!     led_strip4
//!         .animate([
//!             (Frame::filled(colors::RED), frame_duration),
//!             (Frame::filled(colors::GREEN), frame_duration),
//!             (Frame::filled(colors::BLUE), frame_duration),
//!         ])
//!         .await?;
//!
//!     Ok(future::pending().await) // run forever
//! }
//! ```
//! Example of what the [`led_strip!`](crate::led_strip!) macro generates.
//!
//! This module demonstrates the exact struct shape, associated constants, and constructor signature
//! produced by the [`led_strip!`](crate::led_strip!) macro. It uses the macro to generate a real struct
//! so you can inspect the generated API in documentation. All methods visible on this struct are
//! available on any strip created with the [`led_strip!`](crate::led_strip!) macro.
//!
//! # Configuration (Sample Values)
//!
//! This example uses:
//! - **`pin: PIN_3`** — GPIO pin (sample; use any available pin)
//! - **`len: 48`** — 48 LEDs (sample; adjust for your strip size)
//! - **`pio: PIO0` (default)** — PIO block (sample; switch to PIO1 if needed)
//! - **`dma: DMA_CH0` (default)** — DMA channel (sample; pick any available channel)
//!
//! See [`led_strip!`](crate::led_strip!) macro documentation for all available options.
//!
//! # Example Usage
//!
//! [`LedStripGenerated`] is equivalent to writing this macro invocation:
//!
//! ```ignore
//! led_strip! {
//!     LedStripGenerated {
//!         pin: PIN_3,       // ← Sample pin
//!         len: 48,          // ← Sample size
//!         // pio and dma use defaults; customize as needed
//!     }
//! }
//! ```
//!
//! After creation, all these methods are available (sample calls):
//!
//! ```ignore
//! let strip = LedStripGenerated::new(p.PIN_3, p.PIO0, p.DMA_CH0, spawner)?;
//!
//! // Write a single frame
//! let mut frame = Frame::filled(colors::RED);
//! frame[0] = colors::BLUE;  // Deref to [Rgb; N] for pixel access
//! strip.write_frame(&frame).await?;
//!
//! // Animate frames
//! strip.animate([
//!     (Frame::filled(colors::RED), Duration::from_millis(500)),
//!     (Frame::filled(colors::GREEN), Duration::from_millis(500)),
//! ]).await?;
//! ```
//!
//! # Generated Members
//!
//! - `const LEN: usize = 48` — The number of LEDs in the strip (changes based on `len` parameter)
//! - `const MAX_BRIGHTNESS: u8` — Maximum brightness (limited by power budget, see [`Current`](crate::led_strip::Current))
//! - `async fn new(pin, pio, dma, spawner) -> Result<Self>` — Constructor that sets up the LED strip

use crate::led_strip;

led_strip! {
    LedStripGenerated {
        pin: PIN_3,
        len: 48,
    }
}
