//! A device abstraction for rectangular NeoPixel-style (WS2812) LED panel displays.
//!
//! See [`Led2dGenerated`] for a concrete generated-struct example and usage.

#[cfg(not(feature = "host"))]
use crate::led_strip::{Current, Gamma};
#[cfg(not(feature = "host"))]
use crate::led2d;
#[cfg(not(feature = "host"))]
use crate::led2d::layout::LedLayout;

// 12×4 panel wired serpentine column-major (sample configuration)
#[cfg(not(feature = "host"))]
const LED_LAYOUT: LedLayout<48, 12, 4> = LedLayout::serpentine_column_major();

#[cfg(all(not(doc), not(feature = "host")))]
led2d! {
    Led2dGenerated,
    // PIO resource (default: PIO0)
    pio: PIO0,
    // GPIO pin for LED data signal
    pin: PIN_3,
    // DMA channel for LED data transfer (default: DMA_CH0)
    dma: DMA_CH0,
    // Panel dimensions
    width: 12,
    height: 4,
    // LED layout mapping (see [`layout::LedLayout`](crate::led2d::layout::LedLayout) for options)
    led_layout: LED_LAYOUT,
    // Power budget (default: unlimited)
    max_current: Current::Unlimited,
    // Gamma correction mode (default: Gamma2_2)
    gamma: Gamma::Gamma2_2,
    // Maximum animation frames (default: 16)
    max_frames: 16,
    // Font variant (see [`Led2dFont`](crate::led2d::Led2dFont) for available fonts)
    font: Font3x4Trim,
}

#[cfg(doc)]
#[doc = concat!(
    "A NeoPixel-style (WS2812) LED panel generated by the [`led2d!`] macro.\n\n",
    "**This is a concrete example.** When you write your own [`led2d!`] invocation, the compiler generates \n",
    "a struct with *your chosen name* and your specified panel dimensions. \n",
    "Any struct generated by [`led2d!`] has the same interface and methods you see documented here.\n\n",
    "## Configuration\n\n",
    "Generated structs are specialized for their exact use case:\n\n",
    "- **Panel dimensions** — Set via the `width` and `height` parameters in your [`led2d!`] invocation.\n",
    "- **LED layout mapping** — Configured via `led_layout`. See [`LedLayout`](crate::led2d::layout::LedLayout) for layout options and how to create custom mappings.\n",
    "- **[PIO](crate#glossary) resource and [DMA](crate#glossary) channel** — Customized to the pins and channels you specify.\n",
    "- **Power limiting, gamma correction, and max animation frames** — Configured via `max_current`, `gamma`, and `max_frames`. See the [`led2d!`] macro documentation for complete details.\n",
    "- **Fonts** — Set via `font`. See [`Led2dFont`](crate::led2d::Led2dFont) for available font choices.\n\n",
    "# Example: Write Text\n\n",
    "In this example, we render text on a 12×4 panel. Here, the generated struct is named `Led12x4`.\n\n",
    "```rust,no_run\n",
    "# #![no_std]\n",
    "# #![no_main]\n",
    "# use panic_probe as _;\n",
    "# use core::convert::Infallible;\n",
    "# use core::future;\n",
    "# use core::result::Result::Ok;\n",
    "# use embassy_executor::Spawner;\n",
    "# use embassy_rp::init;\n",
    "use device_kit::{Result, led2d, led2d::layout::LedLayout, led_strip::colors};\n\n",
    "const LED_LAYOUT_12X4: LedLayout<48, 12, 4> = LedLayout::serpentine_column_major();\n\n",
    "led2d! {\n",
"    pub Led12x4,                         // Struct name and visibility\n",
    "    pin: PIN_3,                          // GPIO pin for LED data signal\n",
    "    width: 12,                           // Panel dimensions\n",
    "    height: 4,\n",
    "    led_layout: LED_LAYOUT_12X4,         // LED layout mapping\n",
    "    font: Font3x4Trim,                   // Font variant\n",
    "}\n\n",
    "# #[embassy_executor::main]\n",
    "# pub async fn main(spawner: Spawner) -> ! {\n",
    "#     let err = example(spawner).await.unwrap_err();\n",
    "#     core::panic!(\"{err}\");\n",
    "# }\n",
    "async fn example(spawner: Spawner) -> Result<Infallible> {\n",
    "    let p = init(Default::default());\n\n",
    "    let led12x4 = Led12x4::new(p.PIN_3, p.PIO0, p.DMA_CH0, spawner)?;\n\n",
    "    let colors = [colors::RED, colors::GREEN, colors::BLUE];\n",
    "    led12x4.write_text(\"Rust\", &colors).await?; // Colors cycle as needed.\n",
    "    future::pending().await // run forever\n",
    "}\n",
    "```\n\n",
)]
pub struct Led2dGenerated;

#[cfg(doc)]
/// Static resources for `Led2dGenerated`.
///
/// See [`Led2dGenerated`] for usage.
pub struct Led2dGeneratedStatic {
    led2d_static: crate::led2d::Led2dStatic<48, 16>,
}

#[cfg(doc)]
/// Frame type for `Led2dGenerated`.
///
/// See [`Led2dGenerated`] for usage.
pub type Led2dGeneratedFrame = crate::led2d::Frame<12, 4>;

#[cfg(doc)]
/// LED strip type generated by `led2d!` for this example.
///
/// See [`Led2dGenerated`] for usage.
pub struct Led2dGeneratedLedStrip;

#[cfg(doc)]
impl Led2dGenerated {
    /// Number of columns in the panel.
    pub const WIDTH: usize = 12;
    /// Number of rows in the panel.
    pub const HEIGHT: usize = 4;
    /// Total number of LEDs in this panel (WIDTH * HEIGHT).
    pub const LEN: usize = 48;
    /// Maximum brightness level, automatically limited by the power budget specified in `max_current`.
    ///
    /// We assume each LED draws 60 mA at full brightness. The actual limit depends on
    /// the power budget you specified in the [`led2d!`] macro. This constant is the result
    /// of calculating how much brightness is safe given that budget and the number of LEDs.
    pub const MAX_BRIGHTNESS: u8 =
        crate::led_strip::Current::Unlimited.max_brightness(Self::LEN as u32 * 60);
    /// Maximum animation frames supported for this panel.
    pub const MAX_FRAMES: usize = 16;

    /// Create static resources.
    ///
    /// See [`Led2dGenerated`] for usage.
    #[must_use]
    #[doc(hidden)]
    pub const fn new_static() -> Led2dGeneratedStatic {
        Led2dGeneratedStatic {
            led2d_static: crate::led2d::Led2dStatic::new_static(),
        }
    }

    /// Create a new blank (all black) frame.
    ///
    /// See [`Led2dGenerated`] for usage.
    #[must_use]
    pub const fn new_frame() -> Led2dGeneratedFrame {
        crate::led2d::Frame::new()
    }

    /// Create a new LED panel instance of the struct type
    /// defined by [`led2d!`].
    ///
    /// See [`Led2dGenerated`] for example usage.
    ///
    /// The `pin`, `pio`, and `dma` parameters must correspond to the
    /// GPIO pin, PIO resource, and DMA channel specified in the macro.
    ///
    /// The [`led2d!`] macro defaults to `PIO0` and `DMA_CH0` if not specified.
    ///
    /// # Parameters
    ///
    /// - `pin`: GPIO pin for LED data signal
    /// - `pio`: PIO resource
    /// - `dma`: DMA channel for LED data transfer
    /// - `spawner`: Task spawner for background operations
    pub fn new(
        pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_3>,
        pio: embassy_rp::Peri<'static, embassy_rp::peripherals::PIO0>,
        dma: embassy_rp::Peri<'static, embassy_rp::peripherals::DMA_CH0>,
        spawner: embassy_executor::Spawner,
    ) -> crate::Result<Self> {
        let _ = (pin, pio, dma, spawner);
        Ok(Self)
    }

    /// Create a new LED panel instance from a strip.
    ///
    /// See [`Led2dGenerated`] for usage.
    /// cmk000 docs needed
    pub fn from_strip(
        led_strip: &'static Led2dGeneratedLedStrip,
        spawner: embassy_executor::Spawner,
    ) -> crate::Result<Self> {
        let _ = (led_strip, spawner);
        Ok(Self)
    }

    /// Render a fully defined frame to the panel.
    ///
    /// See [`Led2dGenerated`] for usage.
    pub async fn write_frame(&self, frame: Led2dGeneratedFrame) -> crate::Result<()> {
        let _ = frame;
        Ok(())
    }

    /// Loop through a sequence of animation frames.
    ///
    /// The animation cycles through the provided frames, displaying each for the specified duration.
    /// The animation runs forever in a loop. The number of frames is limited by the `max_frames`
    /// parameter from the [`led2d!`] macro.
    ///
    /// See [`Led2dGenerated`] for usage.
    pub async fn animate(
        &self,
        frames: impl IntoIterator<Item = (Led2dGeneratedFrame, embassy_time::Duration)>,
    ) -> crate::Result<()> {
        let _ = frames;
        Ok(())
    }

    /// Render text into a frame using the configured font and spacing.
    ///
    /// See [`Led2dGenerated`] for usage.
    pub fn write_text_to_frame(
        &self,
        text: &str,
        colors: &[smart_leds::RGB8],
        frame: &mut Led2dGeneratedFrame,
    ) -> crate::Result<()> {
        let _ = (text, colors, frame);
        Ok(())
    }

    /// Render text and display it on the LED panel.
    ///
    /// See [`Led2dGenerated`] for usage.
    pub async fn write_text(&self, text: &str, colors: &[smart_leds::RGB8]) -> crate::Result<()> {
        let _ = (text, colors);
        Ok(())
    }
}
