// @generated by `cargo xtask led2d-generated` or `cargo check-all`. Do not edit by hand.
//! A device abstraction for rectangular NeoPixel-style (WS2812) LED panel displays.
//!
//! This file is auto-generated by `cargo xtask led2d-generated`.
//! See the [`mod@crate::led2d`] module docs for usage and examples.

#[cfg(not(feature = "host"))]
use crate::led_strip::{Current, Gamma};
#[cfg(not(feature = "host"))]
use crate::led2d;
#[cfg(not(feature = "host"))]
use crate::led2d::layout::LedLayout;

// 12×4 panel wired serpentine column-major (sample configuration)
#[cfg(not(feature = "host"))]
const LED_LAYOUT: LedLayout<48, 12, 4> = LedLayout::serpentine_column_major();

#[cfg(all(not(doc), not(feature = "host")))]
led2d! {
    Led2dGenerated,
    // PIO resource (default: PIO0)
    pio: PIO0,
    // GPIO pin for LED data signal
    pin: PIN_3,
    // DMA channel for LED data transfer (default: DMA_CH0)
    dma: DMA_CH0,
    // Panel dimensions
    width: 12,
    height: 4,
    // LED layout mapping (see [`layout::LedLayout`](crate::led2d::layout::LedLayout) for options)
    led_layout: LED_LAYOUT,
    // Power budget (default: unlimited)
    max_current: Current::Unlimited,
    // Gamma correction mode (default: Gamma2_2)
    gamma: Gamma::Gamma2_2,
    // Maximum animation frames (default: 16)
    max_frames: 16,
    // Font variant (see [`Led2dFont`](crate::led2d::Led2dFont) for available fonts)
    font: Font3x4Trim,
}

#[cfg(doc)]
/// Auto-generated example type for rustdoc.
///
/// See the [`mod@crate::led2d`] module docs for usage.
pub struct Led2dGenerated;

#[cfg(doc)]
use crate::Result;
#[cfg(doc)]
use crate::led_strip::Rgb;
#[cfg(doc)]
use crate::led2d::{Frame2d, Led2dStatic};

#[cfg(doc)]
/// Static resources for `Led2dGenerated`.
///
/// See the [`mod@crate::led2d`] module docs for usage.
pub struct Led2dGeneratedStatic {
    led2d_static: Led2dStatic<48, 16>,
}

#[cfg(doc)]
/// LED strip type generated by `led2d!` for this example.
///
/// See the [`mod@crate::led2d`] module docs for usage.
pub struct Led2dGeneratedLedStrip;

#[cfg(doc)]
impl Led2dGenerated {
    /// Number of columns in the panel.
    pub const WIDTH: usize = 12;
    /// Number of rows in the panel.
    pub const HEIGHT: usize = 4;
    /// Total number of LEDs in this panel (WIDTH * HEIGHT).
    pub const LEN: usize = 48;
    /// Maximum brightness level, automatically limited by the power budget specified in `max_current`.
    ///
    /// We assume each LED draws 60 mA at full brightness. The actual limit depends on
    /// the power budget you specified in the [`led2d!`] macro. This constant is the result
    /// of calculating how much brightness is safe given that budget and the number of LEDs.
    pub const MAX_BRIGHTNESS: u8 = Current::Unlimited.max_brightness(Self::LEN as u32 * 60);
    /// Maximum animation frames allowed.
    pub const MAX_FRAMES: usize = 16;

    /// Create static resources.
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    #[must_use]
    #[doc(hidden)]
    pub const fn new_static() -> Led2dGeneratedStatic {
        Led2dGeneratedStatic {
            led2d_static: Led2dStatic::new_static(),
        }
    }

    /// Create a new LED panel instance of the struct type
    /// defined by [`led2d!`].
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    ///
    /// The `pin`, `pio`, and `dma` parameters must correspond to the
    /// GPIO pin, PIO resource, and DMA channel specified in the macro.
    ///
    /// The [`led2d!`] macro defaults to `PIO0` and `DMA_CH0` if not specified.
    ///
    /// # Parameters
    ///
    /// - `pin`: GPIO pin for LED data signal
    /// - `pio`: PIO resource
    /// - `dma`: DMA channel for LED data transfer
    /// - `spawner`: Task spawner for background operations
    pub fn new(
        pin: embassy_rp::Peri<'static, embassy_rp::peripherals::PIN_3>,
        pio: embassy_rp::Peri<'static, embassy_rp::peripherals::PIO0>,
        dma: embassy_rp::Peri<'static, embassy_rp::peripherals::DMA_CH0>,
        spawner: embassy_executor::Spawner,
    ) -> Result<Self> {
        let _ = (pin, pio, dma, spawner);
        Ok(Self)
    }

    /// Create a new LED panel instance from a strip.
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    pub(crate) fn from_strip(
        led_strip: &'static Led2dGeneratedLedStrip,
        spawner: embassy_executor::Spawner,
    ) -> Result<Self> {
        let _ = (led_strip, spawner);
        Ok(Self)
    }

    /// Write a frame to the LED panel.
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    pub async fn write_frame(
        &self,
        frame: Frame2d<{ Self::WIDTH }, { Self::HEIGHT }>,
    ) -> Result<()> {
        let _ = frame;
        Ok(())
    }

    /// Write text to the LED panel.
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    pub async fn write_text(&self, text: &str, colors: &[Rgb]) -> Result<()> {
        let _ = (text, colors);
        Ok(())
    }

    /// Write text into a frame.
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    pub fn write_text_to_frame(
        &self,
        text: &str,
        colors: &[Rgb],
        frame: &mut Frame2d<{ Self::WIDTH }, { Self::HEIGHT }>,
    ) -> Result<()> {
        let _ = (text, colors, frame);
        Ok(())
    }

    /// Animate frames on the LED panel.
    ///
    /// See the [`mod@crate::led2d`] module docs for usage.
    pub async fn animate<const N: usize>(
        &self,
        frames: [(
            Frame2d<{ Self::WIDTH }, { Self::HEIGHT }>,
            embassy_time::Duration,
        ); N],
    ) -> Result<()> {
        let _ = frames;
        Ok(())
    }
}
